Document: psec-freeradius-debug-logger
Title: Debian psec-freeradius-debug-logger Manual
Author: <insert document author here>
Abstract: This manual describes what psec-freeradius-debug-logger is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/psec-freeradius-debug-logger/psec-freeradius-debug-logger.sgml.gz

Format: postscript
Files: /usr/share/doc/psec-freeradius-debug-logger/psec-freeradius-debug-logger.ps.gz

Format: text
Files: /usr/share/doc/psec-freeradius-debug-logger/psec-freeradius-debug-logger.text.gz

Format: HTML
Index: /usr/share/doc/psec-freeradius-debug-logger/html/index.html
Files: /usr/share/doc/psec-freeradius-debug-logger/html/*.html
